# Generated by Django 3.0.5 on 2023-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='elevator_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elevator',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=10),
        ),
    ]
